project/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace project.Models
{
    public class Car
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int      Id        { get; set; }
        public string   Brand { get; set; }
        public string   Name      { get; set; }
        public decimal  Price     { get; set; }
        public string   ImageUrl  { get; set; }
        public string   Category  { get; set; }
        public int Year { get; set; }
        public int SoldNumber { get; set; }
    }
}

project/Models/MobileContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace project.Models
{
    public class MobileContext:DbContext
    {
        public MobileContext() : base("MobileDbConnection") { }
        public DbSet<Car> Cars { get; set; }
    }
}

project/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using project.Models;
namespace project.Controllers
{
    public class CarController : Controller
    {
        MobileContext db = new MobileContext();

        //與路由1「Car」對應
        [OutputCache(Duration = 60)]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CarsList()
        {
            return View();
        }
        public ActionResult CarsListDB()
        {
            //讀取Car資料表，並依Category車類型排序
            var cars = db.Cars.OrderBy(x => x.Category).ToList();
            return View(cars);
        }

        //與路由2「Car/Brand/{brand}」對應
        //以品牌找尋汽車
        //[OutputCache(Duration = 60, Location = OutputCacheLocation.Any)]
        //[OutputCache(Duration = 60)]
        public ActionResult FindBrand(string brand)
        {
            List<Car> cars = null;

            if (string.IsNullOrEmpty(brand) || brand.Trim().ToUpper() == "ALL")
            {
                //找出所有品牌汽車
                cars = (from c in db.Cars
                        select c).ToList();

                ViewBag.Header = "所有品牌汽車";
            }
            else
            {
                //找出該品牌汽車
                cars = (from c in db.Cars
                        where c.Brand == brand
                        select c).ToList();
            }

            if (cars.Count == 0)
            {
                return Content("找不到此品牌汽車");
            }
            else
            {
                ViewBag.Header = cars[0].Brand;
            }

            return View(cars);
        }

        public ActionResult FindCategory(string category)
        {
            if (string.IsNullOrEmpty(category))
            {
                return Content("請提供汽車分類名稱!");
            }

            //找出所有該類型汽車
            var cars = (from c in db.Cars
                        where c.Category == category
                        select c).ToList();

            if (cars.Count == 0)
            {
                return Content("找不到此類型的車!");
            }

            return View(cars);
        }

        public ActionResult FindId(int? Id)
        {
            if (Id == null)
            {
                return Content("請提供汽車Id!");
            }

            Car car = db.Cars.Find(Id);
            if (car == null)
            {
                return Content("查無此Id編號汽車!");
            }

            return View(car);
        }

        //與路由5「Car/Year/{year}」對應
        //以年份找尋汽車
        //[OutputCache(Duration = 60, Location = OutputCacheLocation.ServerAndClient)]
        public ActionResult FindYear(int? year)
        {
            if (year == null)
            {
                return Content("找車請提供年份!");
            }

            //找出所有該類型汽車
            var cars = (from c in db.Cars
                        where c.Year == year
                        orderby c.Brand
                        select c).ToList();

            if (cars.Count == 0)
            {
                //return HttpNotFound("Can not find any car of this year.");
                return Content("找不到這年份的車!");
            }

            return View(cars);
        }

        //與路由6「Car/Brand-Year/{brand}-{year}」對應
        //以品牌及年份的組合找尋汽車
        //[OutputCache(Duration = 60, Location = OutputCacheLocation.Downstream)]
        [OutputCache(Duration = 60)]
        public ActionResult FindBrandYear(string brand, int year)
        {
            List<Car> cars = (from c in db.Cars
                              where c.Brand == brand && c.Year == year
                              select c).ToList();

            if (cars.Count == 0)
            {
                return Content("找不到此Brand-Year汽車");
            }

            ViewBag.Header = brand;

            return View("FindBrand", cars);
        }

        //與路由7「Car/TopSales/{topnumber}」對應
        //查詢銷售前幾名汽車
        //[OutputCache(Duration = 60, Location = OutputCacheLocation.Downstream)]
        public ActionResult TopSales(int topnumber)
        {
            //找出所有該類型汽車
            var cars = (from c in db.Cars
                        orderby c.SoldNumber descending
                        select c).Take(topnumber).ToList();

            if (cars.Count == 0)
            {
                //return HttpNotFound("Can not find any car of this year.");
                return Content("找不到Top Sales數據!");
            }

            ViewBag.TopSales = topnumber;
            return View(cars);
        }

        public ActionResult GetRouteData(string RouteParam)
        {
            //讀取Request請求的URL
            var RawUrl = Request.RawUrl;
            var rawUrl = HttpContext.Request.RawUrl;
            var rawurl = ControllerContext.RequestContext.HttpContext.Request.RawUrl;

            //因為路由的Url屬性為非公開成員, 故透過Reflection讀取Url Pattern設定值
            var route = RouteData.Route;
            var UrlPattern = route.GetType().GetProperty("Url").GetValue(route);

            //透過RouteData.Values讀取路由參數
            var controller = RouteData.Values["controller"];
            var action = RouteData.Values["action"];
            var routeParameter = RouteData.Values["RouteParam"];

            /*這樣也能讀取
            var Controller = ControllerContext.RouteData.Values["controller"];
            var Action = ControllerContext.RouteData.Values["action"];
            var RouteParameter = ControllerContext.RouteData.Values["RouteParam"];
            */

            return View();
        }

        public ActionResult Repair()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }

        //Table: Reflow
        public ActionResult RepairReflow()
        {
            return View();
        }
    }
}

project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

project/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace project.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl)
        {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

project/Views/Car/About.cshtml
@{
    ViewBag.Title = "About";
}

<div data-role="header" data-add-back-btn="true">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>關於我們</h1>
</div>

<div role="main" class="ui-content">
    <h1>經營理念</h1>
    <div>
        <img src="~/Assets/images/cars/VW_Beetle.jpeg"/>
    </div>
    <p>
        本公司具備多年汽車銷售及維修經驗，本著顧客至上的理念，
        為客戶提供最好的服務，讓您獲得最佳的服務體驗。
    </p>
</div>

@section topCSS{
    <style>
        div.ui-content h1 {
        text-align:center;
        color:white;
        background-color:dodgerblue;
        border-radius:10px;
        }

        img {
            max-width:100%;
            width:100%;
            height:auto;
            border-radius:10px;
            border:1px solid black;
            text-shadow:none;
        }
    </style>
}

project/Views/Car/CarsList.cshtml
@{
    ViewBag.Title = "CarsList";
}
<div data-role="header" data-add-back-btn="true">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>各類型汽車及價格參考</h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        <!--轎車-->
        <li data-role="list-divider"><h1>轎車</h1></li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Mercedes_AMG_S63.jpg" />
                <h2>Mercedes-AMG S63</h2>
                <p>價格:$145,695</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Audi_S8.jpg" />
                <h2>Audi S8</h2>
                <p>價格:$116,875</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/BMW_M3.jpg" />
                <h2>BMW M3</h2>
                <p>價格:$66,495</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/AlfaRomeo_GiuliaQuadrifoglio.jpg" />
                <h2>Alfa Romeo Giulia Quadrifoglio</h2>
                <p>價格:$73,595</p>
            </a>
        </li>

        <!--SUV-->
        <li data-role="list-divider"><h1>SUV</h1></li>
        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/MercedesBenz_GLS.jpg" />
                <h2>MercedesBenz GLS Class</h2>
                <p>價格:$68,045</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Porsche_Cayenne.jpg" />
                <h2>Porsche Cayenne</h2>
                <p>價格:$60,650</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Honda_CRV.jpg" />
                <h2>Honda CR-V</h2>
                <p>價格:$24,985</p>
            </a>
        </li>

        <!--跑車-->
        <li data-role="list-divider"><h1>跑車</h1></li>
        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Bugatti_Chiron.jpg" />
                <h2>Bugatti Chiron</h2>
                <p>價格:$2,998,000</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Lamborghini_Huracan.jpg" />
                <h2>Lamborghini Huracan</h2>
                <p>價格:$203,295</p>
            </a>
        </li>

        <li data-icon="false">
            <a href="#">
                <img src="~/Assets/images/cars/Porsche_718Boxster.jpg" />
                <h2>Porsche 718 Boxster</h2>
                <p>價格:57,050</p>
            </a>
        </li>

    </ul>
</div>

project/Views/Car/CarsListDB.cshtml
@model IEnumerable<project.Models.Car>

@{
    ViewBag.Title = "CarsListDB";
    var Category = "";
}

<div data-role="header" data-add-back-btn="true" data-position="fixed">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>各類型汽車及價格參考</h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        @foreach (var car in Model)
        {
            //替每類車建立List divider
            if (Category != car.Category)
            {
                Category = car.Category;

                <li data-role="list-divider"><h1>@car.Category</h1></li>
            }

            //顯示每筆車的資料
            <li data-icon="false">
                <a href="#">
                    <img src="~/Assets/Images/cars/@car.ImageUrl" />
                    <h2>@car.Name</h2>
                    <p>價格:$@car.Price</p>
                </a>
            </li>
        }
    </ul>
</div>

project/Views/Car/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div data-role="header" data-add-back-btn="true">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>聯絡方式</h1>
</div>

<div role="main" class="ui-content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        <li data-role="list-divider"><h1>免費客服電話</h1></li>
        <li data-icon="phone"><a href="tel:080080123">免費客服電話080080123</a></li>
        <li data-role="list-divider"><h1>Mobile行動電話</h1></li>
        <li data-role="phone"><a href="tel:+886925154286">行動電話:+886925154286</a></li>
        <li data-role="list-divider"><h1>SMS簡訊</h1></li>
        <li data-role="phone"><a href="sms://+886925154286">發送簡訊到客服</a></li>
        <li data-role="list-divider"><h1>寫Email給客服部</h1></li>
        <li data-role="phone"><a href="mailto:services@carseller.com.tw">Email: services@carseller.com.tw</a></li>
        <li data-role="list-divider"><h1>Facetime</h1></li>
        <li data-role="phone"><a href="facetime:dotnetcool@gmail.com">與客服人員Facetime視訊</a></li>
        <li data-role="list-divider"><h1>Line</h1></li>
        <li data-role="phone"><a href="line://msg/text/Hello!這是測試訊息請忽略">用Line傳訊給客服人員</a></li>
        <li data-role="list-divider"><h1>Skype</h1></li>
        <li data-icon="video"><a href="skype:echo123?call">Skype通話測試</a></li>
    </ul>
</div>

project/Views/Car/FindBrand.cshtml
@model IEnumerable<project.Models.Car>

@{
    ViewBag.Title = "Brand";
    var Brand = "";
}

<div data-role="header" data-add-back-btn="true" data-position="fixed">
    <h1>廠牌 : @ViewBag.Header </h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        @if (Model != null)
        {
            foreach (var car in Model)
            {

                //建立List divider
                if (Brand != car.Brand)
                {
                    Brand = car.Brand;

                    <li data-role="list-divider"><h1>@car.Brand</h1></li>
                }

                //呼叫Partial View部分檢視,以顯示每筆車的資料
                 @Html.Partial("CarDetailPartial", car)
            }
        }
    </ul>
</div>

project/Views/Car/FindBrandYear.cshtml
@{
    ViewBag.Title = "FindBrandYear";
}

<h2>FindBrandYear</h2>

project/Views/Car/FindCategory.cshtml
@model IEnumerable<project.Models.Car>

@{
    ViewBag.Title = "FindCategory";
    var Category = "";
}

<div data-role="header" data-add-back-btn="true" data-position="fixed">
    <h1>汽車類型 : @Model.FirstOrDefault().Category</h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        @foreach (var car in Model)
        {
            //建立List divider
            if (Category != car.Category)
            {
                Category = car.Category;

                <li data-role="list-divider"><h1>@car.Category</h1></li>
            }

            //呼叫Partial View部分檢視,以顯示每筆車的資料
            @Html.Partial("CarDetailPartial", car)
        }
    </ul>
</div>

project/Views/Car/FindId.cshtml
@model project.Models.Car

@{
    ViewBag.Title = "Find car by Id";
}

<div data-role="header">
    <h1>汽車Id 編號 : @Model.Id</h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        <li data-role="list-divider"><h1>@Model.Category</h1></li>

        <!--呼叫Partial View部分檢視,以顯示每筆車的資料-->
        @Html.Partial("CarDetailPartial", Model)
    </ul>
</div>

project/Views/Car/FindYear.cshtml
@model IEnumerable<project.Models.Car>

@{
    ViewBag.Title = "Find by Year";
    var Brand = "";
}

<div data-role="header" data-add-back-btn="true" data-position="fixed">
    <h1>年份 : @Model.FirstOrDefault().Year 年</h1>
</div>

<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        @foreach (var car in Model)
        {
            //建立List divider
            if (Brand != car.Brand)
            {
                Brand = car.Brand;

                <li data-role="list-divider"><h1>@car.Brand</h1></li>
            }

            //呼叫Partial View部分檢視,以顯示每筆車的資料
            @Html.Partial("CarDetailPartial", car)
        }
    </ul>
</div>

project/Views/Car/GetRouteData.cshtml
@{
    ViewBag.Title = "GetRouteData";
}

<h2>GetRouteData</h2>

@{
    //透過Reflection讀取Url Pattern設定值
    var route = ViewContext.RouteData.Route;
    var UrlPattern = route.GetType().GetProperty("Url").GetValue(route);
}

<!--讀取Request請求的URL-->
<h3>URL請求 : @Request.RawUrl</h3>
@*<h3>URL請求 : @ViewContext.RequestContext.HttpContext.Request.RawUrl</h3>*@


<h3>對映路由URL Pattern : @UrlPattern</h3>

<!--逐一讀取路由參數-->
<ul>
    @foreach (var item in ViewContext.RouteData.Values)
    {
        <li>@item.Key : @item.Value</li>
    }
</ul>

<!--或是建立成Partial View-->
@*@Html.Partial("RouteInfoPartial")*@

project/Views/Car/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div data-role="header">
    <h1>汽車情報網</h1>
</div>

<div role="main" class="ui-content">
    <div id="carlogo">
        <img src="~/Assets/Images/cars/ferrari.png" />
    </div>

    <ul data-role="listview" data-inset="true">
        <li><a href="CarsList">汽車款式</a></li>
        <li><a href="Repair">維修保養</a></li>
        <li><a href="Contact">連絡客服</a></li>
        <li><a href="About">關於我們</a></li>
        <li><a href="CarsListDB">汽車款式(資料庫)</a></li>
        @*<li><a href="RepairReflow">維修保養(Table Reflow)</a></li>*@
    </ul>
</div>


@section topCSS{
    <style>
        img {
            max-width: 100%;
            height: auto;
        }

        div#carlogo {
            text-align: center;
            margin-top: 5px;
            margin-bottom: 5px;
        }
    </style>
}

project/Views/Car/Repair.cshtml
@{
    ViewBag.Title = "Repair";
}

<div data-role="header" data-add-back-btn="true">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>維修保養</h1>
</div>

<div role="main" class="ui-content">
    <!--Table: Column Toggle-->
    <table data-role="table" id="table-column-toggle" data-mode="columntoggle" class="ui-responsive table-stroke table-stripe" data-column-btn-text="選擇欄位" data-column-btn-theme="b">
        <caption>汽車維修保養價目表</caption>
        <thead>
            <tr>
                <th data-priority="1">編號</th>
                <th data-priority="critical">維修項目</th>
                <th data-priority="2">小型車</th>
                <th>轎車</th>
                <th data-priority="3">休旅車</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <td>引擎維修</td>
                <td>3000</td>
                <td>3200</td>
                <td>3500</td>
            </tr>
            <tr>
                <th>2</th>
                <td>更換機油</td>
                <td>400</td>
                <td>500</td>
                <td>600</td>
            </tr>
            <tr>
                <th>3</th>
                <td>煞車油更換</td>
                <td>699</td>
                <td>750</td>
                <td>750</td>
            </tr>
        </tbody>
    </table>
</div>

@section topCSS{
    <style>
        .ui-table caption {
            color: black;
            text-align: center;
            opacity: 1;
            text-shadow: none;
            font-size: 1.5em;
        }
    </style>
}

project/Views/Car/RepairReflow.cshtml
@{
    ViewBag.Title = "Repair - Reflow Table";
}

<div data-role="header" data-add-back-btn="true">
    <a href="#" data-role="button" data-rel="back" data-theme="b">返回</a>
    <h1>維修保養</h1>
</div>

<div role="main" class="ui-content">
    <!--Table: Reflow-->
    <table data-role="table" id="table-reflow" data-mode="reflow" class="ui-responsive table-stroke table-stripe">
        <caption>汽車維修保養價目表</caption>
        <thead>
            <tr>
                <th data-priority="1">編號</th>
                <th data-priority="critical">維修項目</th>
                <th data-priority="2">小型車</th>
                <th>轎車</th>
                <th data-priority="3">休旅車</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>1</th>
                <td>引擎維修</td>
                <td>3000</td>
                <td>3200</td>
                <td>3500</td>
            </tr>
            <tr>
                <th>2</th>
                <td>更換機油</td>
                <td>400</td>
                <td>500</td>
                <td>600</td>
            </tr>
            <tr>
                <th>3</th>
                <td>煞車油更換</td>
                <td>699</td>
                <td>750</td>
                <td>750</td>
            </tr>
        </tbody>
    </table>
</div>

@section topCSS{
    <style>
        .ui-table caption {
            color: black;
            text-align: center;
            opacity: 1;
            text-shadow: none;
            font-size: 1.5em;
        }
    </style>
}

project/Views/Car/TopSales.cshtml
@model IEnumerable<project.Models.Car>

@{
    ViewBag.Title = "Top Sales";
    var Brand = "";
}

<div data-role="header" data-add-back-btn="true" data-position="fixed">
    <h1>Top Sales @ViewBag.TopSales</h1>
</div>
TRIZ手作COFFEE
<div data-role="content">
    <ul data-role="listview" data-inset="true" data-theme="a" data-divider-theme="b">
        @foreach (var car in Model)
        {
            //建立List divider
            if (Brand != car.Brand)
            {
                Brand = car.Brand;

                <li data-role="list-divider"><h1>@car.Brand</h1></li>
            }

            //呼叫Partial View部分檢視,以顯示每筆車的資料
            @Html.Partial("CarTopSalesPartial", car)
        }
    </ul>
</div>

project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

project/Views/Shared/CarDetailPartial.cshtml
@model project.Models.Car

<li data-icon="false">
    <a href="#">
        <img src="~/Assets/Images/cars/@Model.ImageUrl" />
        <h2>@Model.Brand @Model.Name - @Model.Year 年款式</h2>
        <p>價格:$@Model.Price</p>
    </a>
</li>

project/Views/Shared/CarTopSalesPartial.cshtml
@model project.Models.Car

<li data-icon="false">
    <a href="#">
        <img src="~/Assets/Images/cars/@Model.ImageUrl" />
        <h2>@Model.Brand @Model.Name - @Model.Year 年款式(共售出 @Model.SoldNumber 輛)</h2>
        <p>價格:$@Model.Price</p>
    </a>
</li>

project/Views/Shared/HeroPartial.cshtml
@model MvcJqueryMobile.Models.Hero

<div data-role="page" id="@Model.PageId">
    <div data-role="header" data-theme="a">
        <h1>LOL英雄人物  -- @Model.Header</h1>
    </div>
    <div role="main" class="ui-content">
        <img src="@Model.ImageUrl" alt="@Model.ImageAlt" />
        <p>
            @Model.Introduction
        </p>
        <div class="video-responsive">
            <iframe src="@Model.VideoUrl" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    <div data-role="footer" data-theme="b" data-position="fixed">
        <h3>@Model.Footer</h3>
    </div>
</div>

project/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <!-- 確保IE使用最新的Rendering mode -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
    @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")

    @RenderSection("topCSS", required: false)
    @RenderSection("topJS", required: false)

    <script>
        $(document).ready(function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
</head>
<body>
    <div data-role="page">
        <div data-role="header">
            <h1>@ViewBag.Header</h1>
        </div>

        <div role="main" class="ui-content">
            @RenderBody()
        </div>

        <div data-role="footer" data-position="fixed">
            <h3>@ViewBag.Footer</h3>
        </div>
    </div>
    @RenderSection("endCSS", required: false)
    @RenderSection("endJS", required: false)
</body>
</html>

project/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}